const fs = require('node:fs');
const path = require('node:path');

const PUBLIC_DIRECTORY = path.join(__dirname, '..', '..', 'public');

const JAVASCRIPT_ASSETS = Object.freeze([
  'app-core.js',
  'renderers-01.js',
  'renderers-02.js',
  'renderers-03.js',
  'renderers-04.js',
  'renderers-05.js',
  'renderers-06.js',
  'renderer-sparse-vector-1570.js',
  'renderer-regex-match-10.js',
  'renderer-wildcard-match-44.js',
  'renderer-maximal-rectangle-85.js',
  'renderer-max-path-sum-124.js',
  'renderer-palindrome-cuts-132.js',
  'renderer-sliding-maximum-239.js',
  'renderer-visible-points-1610.js',
  'renderer-median-finder-295.js',
  'renderer-generate-parentheses-22.js',
  'renderer-remove-invalid-301.js',
  'renderer-burst-balloons-312.js',
  'renderer-longest-increasing-path-329.js',
  'renderer-valid-parentheses-path-2267.js',
  'renderer-split-array-410.js',
  'renderer-all-one-432.js',
  'renderer-freedom-trail-514.js',
  'renderer-cracking-safe-753.js',
  'renderer-special-binary-string-761.js',
  'renderer-basic-calculator-iv-770.js',
  'renderer-race-car-818.js',
  'renderer-k-inverse-pairs-629.js',
  'renderer-strange-printer-664.js',
  'renderer-count-different-palindromic-subsequences-730.js',
  'renderer-cherry-pickup-741.js',
  'renderer-valid-path-1391.js',
  'renderer-server-allocator-9018.js',
  'renderer-text-justification-68.js',
  'renderer-requested-visualizations.js',
  'renderer-vending-machine-change-9012.js',
  'renderer-hard-problems.js',
  'renderer-inform-employees-1376.js',
  'renderer-remove-outermost-1021.js',
  'renderer-score-parentheses-856.js',
  'renderer-min-insertions-1541.js',
  'renderer-locked-parentheses-2116.js',
  'renderer-minimize-expression-2232.js',
  'renderer-different-parentheses-241.js',
  'renderer-apply-substitutions-3481.js',
  'renderer-smallest-infinite-set-2336.js',
  'renderer-special-characters-3121.js',
  'renderer-disappeared-numbers-448.js',
  'renderer-partition-equal-subset-416.js',
  'renderer-valid-parenthesis-string-678.js',
  'renderer-furthest-houses-2078.js',
  'renderer-maximum-distance-1855.js',
  'renderer-prefix-suffix-search-745.js',
  'renderer-prefix-suffix-trie-745.js',
  'renderer-match-substring-replacement-2301.js',
  'renderer-vowel-substrings-3306.js',
  'renderer-to-lower-case-709.js',
  'renderer-defanging-ip-1108.js',
  'renderer-equivalent-string-arrays-1662.js',
  'renderer-goal-parser-1678.js',
  'renderer-reverse-string-ii-541.js',
  'renderer-reverse-words-iii-557.js',
  'renderer-reverse-words-151.js',
  'renderer-valid-anagram-242.js',
  'renderer-find-the-difference-389.js',
  'renderer-longest-palindrome-409.js',
  'renderer-word-pattern-290.js',
  'renderer-frequency-sort-451.js',
  'renderer-close-strings-1657.js',
  'renderer-distinct-triplets-1876.js',
  'renderer-reverse-vowels-345.js',
  'renderer-reverse-only-letters-917.js',
  'renderer-backspace-compare-844.js',
  'script.js',
]);

const STYLESHEET_ASSETS = Object.freeze([
  'style.css',
  'style-01.css',
  'style-02.css',
  'style-03.css',
  'style-04.css',
  'style-05.css',
  'style-06.css',
  'style-07.css',
  'style-08.css',
  'style-09.css',
  'sparse-vector-1570.css',
  'regex-match-10.css',
  'wildcard-match-44.css',
  'maximal-rectangle-85.css',
  'max-path-sum-124.css',
  'palindrome-cuts-132.css',
  'sliding-maximum-239.css',
  'visible-points-1610.css',
  'median-finder-295.css',
  'generate-parentheses-22.css',
  'remove-invalid-301.css',
  'burst-balloons-312.css',
  'longest-increasing-path-329.css',
  'valid-parentheses-path-2267.css',
  'split-array-410.css',
  'all-one-432.css',
  'freedom-trail-514.css',
  'cracking-safe-753.css',
  'special-binary-string-761.css',
  'basic-calculator-iv-770.css',
  'race-car-818.css',
  'k-inverse-pairs-629.css',
  'strange-printer-664.css',
  'count-different-palindromic-subsequences-730.css',
  'cherry-pickup-741.css',
  'valid-path-1391.css',
  'server-allocator-9018.css',
  'text-justification-68.css',
  'requested-visualizations.css',
  'vending-machine-change-9012.css',
  'hard-problems.css',
  'smallest-infinite-set-2336.css',
  'special-characters-3121.css',
  'disappeared-numbers-448.css',
  'partition-equal-subset-416.css',
  'valid-parenthesis-string-678.css',
  'furthest-houses-2078.css',
  'maximum-distance-1855.css',
  'prefix-suffix-search-745.css',
  'prefix-suffix-trie-745.css',
  'match-substring-replacement-2301.css',
  'vowel-substrings-3306.css',
  'debug-controls.css',
  'inform-employees-1376.css',
  'remove-outermost-1021.css',
  'score-parentheses-856.css',
  'min-insertions-1541.css',
  'locked-parentheses-2116.css',
  'minimize-expression-2232.css',
  'different-parentheses-241.css',
  'apply-substitutions-3481.css',
  'to-lower-case-709.css',
  'defanging-ip-1108.css',
  'equivalent-string-arrays-1662.css',
  'goal-parser-1678.css',
  'reverse-string-ii-541.css',
  'reverse-words-iii-557.css',
  'reverse-words-151.css',
  'valid-anagram-242.css',
  'find-the-difference-389.css',
  'longest-palindrome-409.css',
  'word-pattern-290.css',
  'frequency-sort-451.css',
  'close-strings-1657.css',
  'distinct-triplets-1876.css',
  'reverse-vowels-345.css',
  'reverse-only-letters-917.css',
  'backspace-compare-844.css',
]);

const sourceCache = new Map();

function readSource(name, assets) {
  if (!sourceCache.has(name)) {
    sourceCache.set(name, assets
      .map(asset => fs.readFileSync(path.join(PUBLIC_DIRECTORY, asset), 'utf8'))
      .join(''));
  }
  return sourceCache.get(name);
}

function readFrontendJavaScript() {
  return readSource('javascript', JAVASCRIPT_ASSETS);
}

function readFrontendStyles() {
  return readSource('styles', STYLESHEET_ASSETS);
}

function readFrontendIndex() {
  return readSource('index', ['index.html']);
}

module.exports = {
  JAVASCRIPT_ASSETS,
  STYLESHEET_ASSETS,
  readFrontendIndex,
  readFrontendJavaScript,
  readFrontendStyles,
};
